version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=testpw
      - MYSQL_DATABASE=fabric_ca
    volumes:
      - ./fabric-ca-server/ca0/mysql:/var/lib/mysql
    command: --sql-mode=""
    ports:
      - 4000:3306

  fabric-ca-server:
    container_name: ca0
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - ./fabric-ca-server/ca0:/etc/hyperledger/fabric-ca-server
    command: /bin/bash -c 'sleep 15; fabric-ca-server start -b admin:adminpw'
    ports:
      - 7054:7054
    depends_on:
      - mysql

  fabric-ca-client:
    container_name: ca0-client
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/fabric-ca/clients/admin
    volumes:
      - ./fabric-ca-client/ca0/admin:/opt/fabric-ca/clients/admin
    command: /bin/bash -c 'sleep 20; fabric-ca-client enroll -u http://admin:adminpw@fabric-ca-server:7054; sleep 10000'
    depends_on:
      - fabric-ca-server
